name = "kaputt-lab"
main = "src/worker.js"
compatibility_date = "2026-09-18"

[assets]
directory = "../lab"
binding = "ASSETS"
exclude = ["*.test.js"]

[[d1_databases]]
binding = "DB"
database_name = "kaputt-lab"
database_id = "986e5b8a-e0e5-43cd-8db3-48e629fe398a"
migrations_dir = "migrations"
